package manage

import (
	"fmt"
	"os"
	"strings"

	"github.com/hasan714222-debug/ParsTanel/internal/app"
)

type TunnelSpec struct {
	Name      string
	Role      string
	Transport string

	Preset string

	BindAddr      string
	RemoteAddr    string
	Token         string
	Ports         []string
	LoadBalance   bool
	HealthFailover bool
	FallbackAddrs []string

	Nodelay        bool
	Heartbeat      int
	KeepAlive      int
	ChannelSize    int
	ConnectionPool int
	AggressivePool bool
	AcceptUDP      bool
	LogLevel       string
	LogFormat      string

	MuxCon          int
	MuxVersion      int
	MuxFrameSize    int
	MuxRecvBuffer   int
	MuxStreamBuffer int

	KCPMTU          int
	KCPInterval     int
	KCPResend       int
	KCPNoDelay      int
	KCPNoCongestion int
	KCPSndWnd       int
	KCPRcvWnd       int
	KCPAckNoDelay   bool
	KCPDataShards   int
	KCPParityShards int

	PckInterface  string
	PckGatewayMAC string
	PckFlags      []string

	MSS      int
	SoRcvBuf int
	SoSndBuf int

	ProxyProtocol bool

	MaxConnections int
	BandwidthMbps  int

	Sniffer bool
	WebPort int
	WebBind string

	TLSCert    string
	TLSKey     string
	ACMEDomain string
	ACMEEmail  string

	EdgeIP     string
	SimpleAuth bool
	Proxy      string
	LocalAddr  string
	Interface  string
	SOMark     int
	ZeroCopy   bool
}

func monitorBind(configured string) string {
	if configured == "" {
		return "127.0.0.1"
	}
	return configured
}

func (s TunnelSpec) writeTuning(p func(string, ...any)) {
	if s.MSS > 0 {
		p("mss = %d\n", s.MSS)
	}
	if s.SoRcvBuf > 0 {
		p("so_rcvbuf = %d\n", s.SoRcvBuf)
	}
	if s.SoSndBuf > 0 {
		p("so_sndbuf = %d\n", s.SoSndBuf)
	}
}

func (s TunnelSpec) writeKCP(p func(string, ...any)) {
	if !isKCP(s.Transport) {
		return
	}
	p("kcp_mtu = %d\n", s.KCPMTU)
	p("kcp_interval = %d\n", s.KCPInterval)
	p("kcp_resend = %d\n", s.KCPResend)
	p("kcp_nodelay = %d\n", s.KCPNoDelay)
	p("kcp_nocongestion = %d\n", s.KCPNoCongestion)
	p("kcp_sndwnd = %d\n", s.KCPSndWnd)
	p("kcp_rcvwnd = %d\n", s.KCPRcvWnd)
	p("kcp_acknodelay = %t\n", s.KCPAckNoDelay)
	p("kcp_datashards = %d\n", s.KCPDataShards)
	p("kcp_parityshards = %d\n", s.KCPParityShards)
}

func (s TunnelSpec) writePck(p func(string, ...any)) {
	if s.Transport != "pck" {
		return
	}
	if s.PckInterface != "" {
		p("pck_interface = %q\n", s.PckInterface)
	}
	if s.PckGatewayMAC != "" {
		p("pck_gateway_mac = %q\n", s.PckGatewayMAC)
	}
	if len(s.PckFlags) > 0 {
		quoted := make([]string, len(s.PckFlags))
		for i, f := range s.PckFlags {
			quoted[i] = fmt.Sprintf("%q", f)
		}
		p("pck_flags = [%s]\n", strings.Join(quoted, ", "))
	}
}

func isMux(t string) bool {
	return t == "tcpmux" || t == "wsmux" || t == "wssmux" || t == "kcp" || t == "xdi" || t == "pck"
}

func isKCP(t string) bool {
	return t == "kcp" || t == "xdi" || t == "pck"
}

func IsDatagram(t string) bool { return isDatagram(t) }

func isDatagram(t string) bool {
	if strings.HasPrefix(t, "l3/") {
		return true
	}
	if strings.HasPrefix(t, "direct/") {
		return false
	}
	return t == "udp" || t == "kcp" || t == "xdi" || t == "quic" || t == "pck"
}

func supportsProxyProtocol(t string) bool {
	switch t {
	case "tcp", "tcpmux", "kcp", "wsmux", "wssmux", "stealth", "quic", "pck":
		return true
	}
	return false
}

func isWS(t string) bool {
	return t == "ws" || t == "wss" || t == "wsmux" || t == "wssmux"
}

func needsTLS(t string) bool {
	return t == "wss" || t == "wssmux"
}

func validTransport(t string) bool {
	switch t {
	case "tcp", "tcpmux", "udp", "kcp", "ws", "wss", "wsmux", "wssmux", "stealth", "xdi", "quic", "pck":
		return true
	}
	return false
}

func (s TunnelSpec) Render() string {
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	b.WriteString("# Generated by parstanel — do not edit while the service is running.\n")
	p("# name = \"%s\"\n\n", s.Name)

	if s.Role == "server" {
		b.WriteString("[server]\n")
		p("bind_addr = %q\n", s.BindAddr)
		p("transport = %q\n", s.Transport)
		if s.Preset != "" {
			p("preset = %q\n", s.Preset)
		}
		p("token = %q\n", s.Token)
		p("channel_size = %d\n", s.ChannelSize)
		p("keepalive_period = %d\n", s.KeepAlive)
		p("nodelay = %t\n", s.Nodelay)
		p("heartbeat = %d\n", s.Heartbeat)
		p("log_level = %q\n", s.LogLevel)
		if s.LogFormat != "" {
			p("log_format = %q\n", s.LogFormat)
		}
		s.writeTuning(p)
		s.writeKCP(p)
		s.writePck(p)
		p("accept_udp = %t\n", s.AcceptUDP)
		if needsTLS(s.Transport) {
			p("tls_cert = %q\n", s.TLSCert)
			p("tls_key = %q\n", s.TLSKey)
			if s.ACMEDomain != "" {
				p("acme_domain = %q\n", s.ACMEDomain)
				if s.ACMEEmail != "" {
					p("acme_email = %q\n", s.ACMEEmail)
				}
			}
			if s.SimpleAuth {
				p("simple_auth = true\n")
			}
		}
		if isMux(s.Transport) {
			p("mux_con = %d\n", s.MuxCon)
			p("mux_version = %d\n", s.MuxVersion)
			p("mux_framesize = %d\n", s.MuxFrameSize)
			p("mux_recievebuffer = %d\n", s.MuxRecvBuffer)
			p("mux_streambuffer = %d\n", s.MuxStreamBuffer)
		}
		if supportsProxyProtocol(s.Transport) {
			p("proxy_protocol = %t\n", s.ProxyProtocol)
		}
		if s.ZeroCopy {
			p("zero_copy = true\n")
		}
		if s.MaxConnections > 0 {
			p("max_connections = %d\n", s.MaxConnections)
		}
		if s.BandwidthMbps > 0 {
			p("bandwidth_mbps = %d\n", s.BandwidthMbps)
		}
		p("sniffer = %t\n", s.Sniffer)
		if s.WebPort > 0 {
			p("web_port = %d\n", s.WebPort)
			p("web_bind = %q\n", monitorBind(s.WebBind))
		}
		b.WriteString("ports = [\n")
		for _, port := range s.Ports {
			p("    %q,\n", port)
		}
		b.WriteString("]\n")
		return b.String()
	}

	b.WriteString("[client]\n")
	p("remote_addr = %q\n", s.RemoteAddr)
	if len(s.FallbackAddrs) > 0 {
		b.WriteString("fallback_addrs = [\n")
		for _, a := range s.FallbackAddrs {
			p("    %q,\n", a)
		}
		b.WriteString("]\n")
	}
	p("transport = %q\n", s.Transport)
	if s.Preset != "" {
		p("preset = %q\n", s.Preset)
	}
	p("token = %q\n", s.Token)
	p("connection_pool = %d\n", s.ConnectionPool)
	p("aggressive_pool = %t\n", s.AggressivePool)
	p("keepalive_period = %d\n", s.KeepAlive)
	p("nodelay = %t\n", s.Nodelay)
	if s.LoadBalance {
		p("load_balance = true\n")
	}
	if s.HealthFailover {
		p("health_failover = true\n")
	}
	p("retry_interval = %d\n", 3)
	p("dial_timeout = %d\n", 10)
	p("log_level = %q\n", s.LogLevel)
	if s.LogFormat != "" {
		p("log_format = %q\n", s.LogFormat)
	}
	s.writeTuning(p)
	s.writeKCP(p)
	s.writePck(p)
	if isWS(s.Transport) && s.EdgeIP != "" {
		p("edge_ip = %q\n", s.EdgeIP)
	}
	if needsTLS(s.Transport) && s.SimpleAuth {
		p("simple_auth = true\n")
	}
	if s.Proxy != "" {
		p("proxy = %q\n", s.Proxy)
	}
	if s.LocalAddr != "" {
		p("local_addr = %q\n", s.LocalAddr)
	}
	if s.Interface != "" {
		p("interface = %q\n", s.Interface)
	}
	if s.SOMark != 0 {
		p("so_mark = %d\n", s.SOMark)
	}
	if s.ZeroCopy {
		p("zero_copy = true\n")
	}
	if isMux(s.Transport) {
		p("mux_session = %d\n", s.MuxCon)
		p("mux_version = %d\n", s.MuxVersion)
		p("mux_framesize = %d\n", s.MuxFrameSize)
		p("mux_recievebuffer = %d\n", s.MuxRecvBuffer)
		p("mux_streambuffer = %d\n", s.MuxStreamBuffer)
	}
	p("sniffer = %t\n", s.Sniffer)
	if s.WebPort > 0 {
		p("web_port = %d\n", s.WebPort)
		p("web_bind = %q\n", monitorBind(s.WebBind))
	}
	return b.String()
}

func (s TunnelSpec) Save() (string, error) {
	if err := os.MkdirAll(app.ConfigDir, 0755); err != nil {
		return "", err
	}
	if err := os.WriteFile(app.ConfigPath(s.Name), []byte(s.Render()), 0644); err != nil {
		return "", err
	}
	if err := writeUnit(s.Name); err != nil {
		return "", err
	}
	if err := DaemonReload(); err != nil {
		return "", err
	}
	service := app.ServiceName(s.Name)
	if err := StartService(service); err != nil {
		return service, err
	}
	return service, nil
}
